language: node_js
matrix:
  include:
    - node_js: "6"
    - node_js: "8"
    - node_js: "10"
dist: trusty
cache:
  directories:
    - node_modules
install:
  - bash pika install
script:
  - bash pika test
after_success:
  - bash pika coverage
# - (send to coveralls)
# - (send to codecov)
